################################################################################
# PRJ_DIR: project directory, which include api/src/pak/utt/doc; .tmp/.bin
# SRC_DIR: dedicated the source files to build.
# VER_FILE: the output version file.
################################################################################


# option: for ccmake.
option(MSVC_PCH "msvc precompile header file in windows." OFF)
# logging ccmake options.
message("---------------------------------------------------------------------")
message("== ${PROJECT_NAME} ${PROJECT_VERSION} ${PRJ_CFG}")
message("== MSVC_PCH=${MSVC_PCH}")
message("---------------------------------------------------------------------")

# project version config name. "eco_3.2.0_debug".
set(PRJ_CFG ${PROJECT_NAME}_${CMAKE_BUILD_TYPE})
string(TOLOWER ${PRJ_CFG} PRJ_CFG)
# project directory.
set(INC_DIR ${PRJ_DIR}/inc)
set(TMP_DIR ${PRJ_DIR}/.tmp/${PRJ_CFG})
set(BIN_DIR ${PRJ_DIR}/.bin/${PRJ_CFG})
set(PRJX_TARGETX_NAME1 )
set(PRJX_TARGETX_PATH ${INS_DIR})
if (${INS_DIR} STREQUAL "")
    set(PRJX_TARGETX_PATH ${TMP_DIR})
endif()
# project version template file.
configure_file(${CMAKE_CURRENT_SOURCE_DIR}/Version.tpl.h ${PRJ_VER})
# project logging.
message("== PRJ=${PRJ_DIR}")
message("== SRC=${SRC_DIR}")
message("== BIN=${CMAKE_CURRENT_BINARY_DIR}")
message("== TMP=${TMP_DIR}")
message("== MAK=${CMAKE_CURRENT_SOURCE_DIR}")
message("---------------------------------------------------------------------")

# include directory: api/src
include_directories(${INC_DIR})
include_directories(${SRC_DIR})
# include directory: conan cmake generated by "conanfile.txt".
include(${TMP_DIR}/conanbuildinfo.cmake)
include_directories(${CONAN_INCLUDE_DIRS})
# include library: conan libs directory.
link_directories(${CONAN_LIB_DIRS})
link_directories(${CXX_LIB_DIRS})
# include library: logging.
message("== INC_CONAN=${CONAN_INCLUDE_DIRS}")
message("== LIB_CONAN=${CONAN_LIB_DIRS}")
message("---------------------------------------------------------------------")

# pre compiler: protobuf
#set(GRPC_PROTOC ${CONAN_BIN_DIRS_GRPC}/protoc)
#set(GRPC_CPP_PLUGIN ${CONAN_BIN_DIRS_GRPC}/grpc_cpp_plugin)
# pre compiler: msvc pch
if(MSVC_PCH)
    set(PCH_TARGET ${PROJECT_NAME})
    set(PCH_HEADER_FILE ${SRC_DIR}/Pch.h)
    set(PCH_SOURCE_FILE ${SRC_DIR}/Pch.cpp)
    include(${CMAKE_CURRENT_SOURCE_DIR}/msvc_pch.cmake)
endif(MSVC_PCH)

# c++ compiler: c++
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11")
# c++ compiler: warning/error option.
# unuse -Werror for knowing who are warning. 
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wall -Wextra")
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wno-unused-parameter -Wno-switch")
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fvisibility=hidden")
# c++ compiler: debug/release.
set(CMAKE_CXX_FLAGS_DEBUG "${CMAKE_CXX_FLAGS_DEBUG} -ggdb -O0")
set(CMAKE_CXX_FLAGS_RELEASE "${CMAKE_CXX_FLAGS_RELEASE} -Os")
# c++ compiler: shared dll.
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fPIC")
# c++ compiler: "compile_commands.json".(used in vscode c_cpp_properties.json)
set(CMAKE_EXPORT_COMPILE_COMMANDS True)
# c++ compiler: logging
message("== CXX=${CMAKE_CXX_FLAGS}")
message("== CXX_DEBUG=${CMAKE_CXX_FLAGS_DEBUG}")
message("== CXX_RELEASE=${CMAKE_CXX_FLAGS_RELEASE}")
message("---------------------------------------------------------------------")

# c++ target: project name. (exe/so/a)
if(${PRJ_FMT} STREQUAL "exe")
    add_executable(${PROJECT_NAME})
    #set(CXX_TEMP ".exe.${PROJECT_VERSION}")
    #set_target_properties(${PROJECT_NAME} PROPERTIES PREFIX "")
    #set_target_properties(${PROJECT_NAME} PROPERTIES SUFFIX ${CXX_TEMP})
    #set(PRJX_TARGETX_NAME1 "${PROJECT_NAME}${CXX_TEMP}")
elseif(${PRJ_FMT} STREQUAL "lib")
    add_library(${PROJECT_NAME} SHARED)
    #message("${PRJX_TARGETX_PATH}")
elseif(${PRJ_FMT} STREQUAL "static")
    add_library(${PROJECT_NAME} STATIC)
    #set(CXX_TEMP ".a.${PROJECT_VERSION}")
    #set_target_properties(${PROJECT_NAME} PROPERTIES PREFIX "lib")
    #set_target_properties(${PROJECT_NAME} PROPERTIES SUFFIX "${CXX_TEMP}")
    #set(PRJX_TARGETX_NAME1 "lib${PROJECT_NAME}${CXX_TEMP}")
endif()
# c++ target: output name.
# c++ target: include dir.
include_directories(${SRC_DIR})
# c++ target: include cpp files.
set(CXX_TEMP )
file(GLOB_RECURSE CXX_TEMP ${SRC_DIR}/*.cpp)
list(APPEND CXX_FILES ${CXX_TEMP})
file(GLOB_RECURSE CXX_TEMP ${SRC_DIR}/*.cc)
list(APPEND CXX_FILES ${CXX_TEMP})
file(GLOB_RECURSE CXX_TEMP ${SRC_DIR}/*.c)
list(APPEND CXX_FILES ${CXX_TEMP})
# c++ target: exclude cpp files.
list(REMOVE_ITEM CXX_FILES ${CXX_FILES_EXCLUDE})
# c++ target: exclude cpp dirs.
set(CXX_TEMP )
file(GLOB_RECURSE CXX_TEMP ${CXX_DIRS_EXCLUDE}/*.cpp)
list(REMOVE_ITEM CXX_FILES ${CXX_TEMP})
file(GLOB_RECURSE CXX_TEMP ${CXX_DIRS_EXCLUDE}/*.cc)
list(REMOVE_ITEM CXX_FILES ${CXX_TEMP})
file(GLOB_RECURSE CXX_TEMP ${CXX_DIRS_EXCLUDE}/*.c)
list(REMOVE_ITEM CXX_FILES ${CXX_TEMP})
# c++ target: bind to project.
target_sources(${PROJECT_NAME} PRIVATE ${CXX_FILES})
target_link_libraries(${PROJECT_NAME} PRIVATE ${CXX_LIBS})
# c++ target: install.
#set(CXX_TEMP ".so.${PROJECT_VERSION}")

#set_target_properties(${PROJECT_NAME} PROPERTIES OUTPUT_NAME "EcoInstationCool")

set_target_properties(${PROJECT_NAME} PROPERTIES LIBRARY_OUTPUT_DIRECTORY ${INS_DIR})
set_target_properties(${PROJECT_NAME} PROPERTIES ARCHIVE_OUTPUT_DIRECTORY ${INS_DIR})
#set_target_properties(${PROJECT_NAME} PROPERTIES RUNTIME_OUTPUT_DIRECTORY ${INS_DIR})
#set_target_properties(${PROJECT_NAME} PROPERTIES SUFFIX ".so.1.0.2")
#set(PRJX_TARGETX_NAME1 "lib${PROJECT_NAME}${CXX_TEMP}")
set_target_properties(${PROJECT_NAME} PROPERTIES PREFIX "lib")
set_target_properties(${PROJECT_NAME} PROPERTIES SUFFIX ".so.${PROJECT_VERSION}")

message("== CPP=${CXX_FILES}")
message("== LIB=${CXX_LIBS}")
message("== PRJX_TARGETX_PATH=${PRJX_TARGETX_PATH}/${PRJX_TARGETX_NAME1}")
message("== PROJECT_NAME=${PROJECT_NAME}")
message("---------------------------------------------------------------------")
