# get absolute path of 'FILES_DIRS'
function(eco_get_absolute_path FILES_DIRS)
    set(_ABS_TEMPS )
    set(_ABS_TEMP )
    foreach(_TEMP ${FILES_DIRS})
        get_filename_component(_ABS_TEMP ${_TEMP} ABSOLUTE)
        list(APPEND _ABS_TEMPS ${_ABS_TEMP})
    endforeach()
    set(FILES_DIRS ${_ABS_TEMPS})
endfunction()

# include c++ source files in 'SRC_DIRS'
function(eco_src_files_include SRC_FILES SRC_DIRS)
if(SRC_DIRS)
    foreach(_SRC_DIR ${SRC_DIRS})
        set(_CXX_TEMP )
        file(GLOB_RECURSE _CXX_TEMP ${_SRC_DIR}/*.cpp)
        list(APPEND SRC_FILES ${_CXX_TEMP})
        file(GLOB_RECURSE _CXX_TEMP ${_SRC_DIR}/*.cxx)
        list(APPEND SRC_FILES ${_CXX_TEMP})
        file(GLOB_RECURSE _CXX_TEMP ${_SRC_DIR}/*.cc)
        list(APPEND SRC_FILES ${_CXX_TEMP})
        file(GLOB_RECURSE _CXX_TEMP ${_SRC_DIR}/*.c)
        list(APPEND SRC_FILES ${_CXX_TEMP})
    endforeach()
endif()
endfunction()

# exclude c++ source files in 'SRC_DIRS_EXCLUDE'
function(eco_src_files_exclude SRC_FILES SRC_DIRS_EXCLUDE)
if(SRC_DIRS_EXCLUDE)
    foreach(_SRC_DIR ${SRC_DIRS_EXCLUDE})
        set(_CXX_TEMP )
        file(GLOB_RECURSE _CXX_TEMP ${_SRC_DIR}/*.cpp)
        list(REMOVE_ITEM SRC_FILES ${_CXX_TEMP})
        file(GLOB_RECURSE _CXX_TEMP ${_SRC_DIR}/*.cxx)
        list(REMOVE_ITEM SRC_FILES ${_CXX_TEMP})
        file(GLOB_RECURSE _CXX_TEMP ${_SRC_DIR}/*.cc)
        list(REMOVE_ITEM SRC_FILES ${_CXX_TEMP})
        file(GLOB_RECURSE _CXX_TEMP ${_SRC_DIR}/*.c)
        list(REMOVE_ITEM SRC_FILES ${_CXX_TEMP})
    endforeach()
endif()
endfunction()

